# Jekyll Configuration
title: "Sanket Muchhala — AI Engineer & Data Scientist | Machine Learning Expert"
description: "AI Engineer and Data Scientist specializing in machine learning, deep learning, NLP, generative AI, and LLMs. Expert in Python, TensorFlow, PyTorch, AWS, and scalable AI solutions."
author: "Sanket Muchhala"
email: "sanketmuchhala@gmail.com"
url: "https://sanketmuchhala.github.io"
baseurl: ""
image: "/photos/export.png"

# SEO Enhancement
keywords: "AI engineer, data scientist, machine learning engineer, artificial intelligence, deep learning, NLP, natural language processing, Python, TensorFlow, PyTorch, AWS, generative AI, LLMs, data science portfolio"
twitter:
  username: sanketmuchhala
  card: summary_large_image
social:
  name: Sanket Muchhala
  links:
    - https://linkedin.com/in/sanketmuchhala
    - https://github.com/sanketmuchhala
    - https://twitter.com/sanketmuchhala
logo: /photos/export.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
relative_links:
  enabled: true
  collections: true

# Disable Sass processing to avoid architecture issues
sass:
  load_paths: []
  style: compressed

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
  blogs:
    output: true
    permalink: /blogs/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "blogs"
    values:
      layout: "blog"

# Plugins
plugins:
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git/
  - .github/
  - README.md
  - portfolio-nextjs/
  - src/
  - projects/*.html
  - blogs/*.html

# Include files that should be processed
include:
  - _sass
  - _assets
  - photography
  - photos
  - resume
  - favicon.svg
  - ribbons.js
  - script.js
  - script.min.js
  - style.css
  - style.min.css
  - Sanket_Muchhala_Resume.pdf

# SEO
lang: en_US
locale: en_US
timezone: America/New_York

# Enhanced SEO
seo:
  type: Person
  name: "Sanket Muchhala"
  location: "United States"
  jobTitle: "AI Engineer & Data Scientist"
  worksFor: "Progressive Insurance"
  alumniOf: "Indiana University Bloomington"
  knowsAbout: "artificial intelligence, machine learning, data science, deep learning, natural language processing, computer vision, generative AI, LLMs"
